package ru.ragnok123.MCCommandConverter.ir;

import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.Map;

/** Side table: IR node -> "File.java:line" of the DSL call that created it. Used for comments and error messages. */
public final class Sites {
    private Sites() {}
    private static final Map<Object, String> SITES = Collections.synchronizedMap(new IdentityHashMap<>());

    public static <T> T mark(T node) {
        String s = capture();
        if (s != null) SITES.put(node, s);
        return node;
    }

    public static String of(Object node) { return SITES.get(node); }

    /** Give `to` the same call site as `from` (for nodes generated by a pass). */
    public static <T> T copy(Object from, T to) {
        String s = SITES.get(from);
        if (s != null) SITES.put(to, s);
        return to;
    }

    private static String capture() {
        return StackWalker.getInstance().walk(fr -> fr
                .filter(f -> !f.getClassName().startsWith("ru.ragnok123.MCCommandConverter.dsl.")
                        && !f.getClassName().startsWith("ru.ragnok123.MCCommandConverter.ir."))
                .findFirst()
                .map(f -> f.getFileName() + ":" + f.getLineNumber())
                .orElse(null));
    }
}
